#!/bin/sh

# Entware/Keenetic cron.1min runs this wrapper every minute.
# 07:00-00:59 -> every minute
# 01:00-06:59 -> every 30 minutes

hour=$(date +%H)
minute=$(date +%M)

case "$hour" in
    07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|00)
        ;;
    01|02|03|04|05|06)
        case "$minute" in
            00|30) ;;
            *) exit 0 ;;
        esac
        ;;
    *)
        exit 0
        ;;
esac

exec /opt/bin/router-watchdog
